### ISSUE TITLE
studyAssay both in study and process - clarification needed

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-templates#3]
I would need some clarification on what the model expects by including studyAssay in two places.

I do get it for [studyAssay in study](https://github.com/metadatacenter/cedar-templates/blob/master/investigation_template/template/investigation_template.json#L111), but I am a bit unsure for [studyAssay in process (within study)](https://github.com/metadatacenter/cedar-templates/blob/master/investigation_template/template/investigation_template.json#L727).

Thanks!

**Comment by martinjoconnor** [comment]
No longer relevant.
